# Site settings
title: Statamic Themes
email: gareth.redfern@gmail.com
description: >
  A blog with articles, code, and themes to help with your Statamic site building.
  Built for the Statamic community to help you learn tips and tricks with practical
  code examples and discussions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://statamicthemes.com" # the base hostname & protocol for your site
twitter_username: garethredfern
github_username:  garethredfern

# Build settings
markdown: kramdown
permalink: /:title
gems:
  - jekyll-sitemap

#Sass
sass:
  sass_dir: _sass

#Collections
collections:
  articles:
    output: true
    permalink: /:collection/:title/
  snippets:
    output: true
    permalink: /:collection/:title/
  themes:
    output: true
    permalink: /:collection/:title/
  plugins:
    output: true
    permalink: /:collection/:title/
  resources:
    output: true
    permalink: /:collection/:title/
